name: Deploy CI/CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: pawalert
          stage: main
          yaml: |
            name: pawalert
            app: web
            options:
              nodeversion: 20
              spa: true
              buildenv:
                - name: VITE_APP_API_URL
                  value: ${{ secrets.VITE_APP_API_URL }}
                - name: VITE_KAKAO_APP_KEY
                  value: ${{ secrets.VITE_KAKAO_APP_KEY }}
                - name: VITE_APP_WS_URL
                  value: ${{ secrets.VITE_APP_WS_URL }}
              rewrites: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: react-vite
